<a href="https://colab.research.google.com/github/erickzenRASHOLAS/Google-Playstore/blob/main/DF_PlayStore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Cargamos las librerias, dataframe y vemos un poco los contenidos de este**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df=pd.read_csv("googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

**Vemos si hay duplicados**

In [ ]:
df.duplicated().sum()

np.int64(483)

**Verificamos si existen nulos**

In [ ]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

**Al ser casi todas las variables String realizaremos un value counts por cada tabla del data frame para detectar algun dato outliner, esto no se realiza en la columna de app, ya que, esta nos indica el nombre de las aplicaciones y por ende todas son distintas**

In [ ]:
df["Category"].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [ ]:
df[df["Category"]=="1.9"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Aqui se ha detectado una Categoria Outliner, la categoria 1.9**

In [ ]:
df["Rating"].value_counts()

Rating
4.4     1109
4.3     1076
4.5     1038
4.2      952
4.6      823
4.1      708
4.0      568
4.7      499
3.9      386
3.8      303
5.0      274
3.7      239
4.8      234
3.6      174
3.5      163
3.4      128
3.3      102
4.9       87
3.0       83
3.1       69
3.2       64
2.9       45
2.8       42
2.6       25
2.7       25
2.5       21
2.3       20
2.4       19
1.0       16
2.2       14
1.9       13
2.0       12
1.7        8
1.8        8
2.1        8
1.6        4
1.4        3
1.5        3
1.2        1
19.0       1
Name: count, dtype: int64

In [ ]:
df[df["Rating"]==19.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Aqui puede ser engañoso, ya que hay unas que se repiten muy poco, pero en este caso el Outliner es 19.0, ya que, esta tabla solo deberia ir desde el 0 al 5.0**

In [ ]:
df["Reviews"].value_counts()

Reviews
0         596
1         272
2         214
3         175
4         137
         ...
4272        1
5517        1
4057        1
459797      1
68935       1
Name: count, Length: 6002, dtype: int64

In [ ]:
df[df['Reviews']=="0"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
478,Truth or Dare Pro,DATING,NaN,0,20M,50+,Paid,$1.49,Teen,Dating,"September 1, 2017",1.0,4.0 and up
479,"Private Dating, Hide App- Blue for PrivacyHider",DATING,NaN,0,18k,100+,Paid,$2.99,Everyone,Dating,"July 25, 2017",1.0.1,4.0 and up
621,Dating White Girls,DATING,NaN,0,3.6M,50+,Free,0,Mature 17+,Dating,"July 20, 2018",1.0,4.0 and up
623,Geeks Dating,DATING,NaN,0,13M,50+,Free,0,Mature 17+,Dating,"July 10, 2018",1.0,4.1 and up
627,CAM5678 Video Chat,DATING,NaN,0,39M,500+,Free,0,Mature 17+,Dating,"July 13, 2018",5.5.8,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773,FQ India,LIFESTYLE,NaN,0,8.9M,10+,Free,0,Everyone,Lifestyle,"July 31, 2018",7.2.2,4.1 and up
10774,Miss FQ,NEWS_AND_MAGAZINES,NaN,0,36M,10+,Free,0,Everyone,News & Magazines,"April 5, 2018",3.8,4.4 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up
10822,PLMGSS FR,PRODUCTIVITY,NaN,0,3.1M,10+,Free,0,Everyone,Productivity,"December 1, 2017",1,4.4 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up

**Aqui NO hay Outliners, ya que esto solo nos dice la cantidad de personas que han calificado la APP**

In [ ]:
df["Size"].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
552k                     1
885k                     1
1020k                    1
582k                     1
619k                     1
Name: count, Length: 462, dtype: int64

**No existe Outliners, esta columna solo indica el peso de la app y no hay ningun valor extraño**

In [ ]:
df["Installs"].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Free                 1
Name: count, dtype: int64

In [ ]:
df[df["Installs"]=="Free"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [ ]:
df[df["Installs"]=="0+"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4465,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5M,0+,Paid,$1.49,Everyone,Personalization,"July 11, 2018",1.1,4.2 and up
5307,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7M,0+,Paid,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up
5486,AP Series Solution Pro,FAMILY,NaN,0,7.4M,0+,Paid,$1.99,Everyone,Education,"July 30, 2017",1.3,4.0 and up
5945,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33M,0+,Paid,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up
6692,cronometra-br,PRODUCTIVITY,NaN,0,5.4M,0+,Paid,$154.99,Everyone,Productivity,"November 24, 2017",1.0.0,4.1 and up
7434,Pekalongan CJ,SOCIAL,NaN,0,5.9M,0+,Free,0,Teen,Social,"July 21, 2018",0.0.1,4.4 and up
8081,CX Network,BUSINESS,NaN,0,10M,0+,Free,0,Everyone,Business,"August 6, 2018",1.3.1,4.1 and up
8614,Sweden Newspapers,NEWS_AND_MAGAZINES,NaN,0,2.1M,0+,Free,0,Everyone,News & Magazines,"July 7, 2018",1.1,4.4 and up
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
9337,EG | Explore Folegandros,TRAVEL_AND_LOCAL,NaN,0,56M,0+,Paid,$3.99,Everyone,Travel & Local,"January 22, 2017",1.1.1,4.1 and up
9719,EP Cook Book,MEDICAL,NaN,0,3.2M,0+,Paid,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up
9905,Eu sou Rico,FINANCE,NaN,0,2.6M,0+,Paid,$30.99,Everyone,Finance,"January 9, 2018",1.0,4.0 and up
9917,Eu Sou Rico,FINANCE,NaN,0,1.4M,0+,Paid,$394.99,Everyone,Finance,"July 11, 2018",1.0,4.0.3 and up
9934,I'm Rich/Eu sou Rico/أنا غني/我很有錢,LIFESTYLE,NaN,0,40M,0+,Paid,$399.99,Everyone,Lifestyle,"December 1, 2017",MONEY,4.1 and up

**Aqui hay 2 Outliner una siendo Free y la otra 1+, ya que, 1+ es lo mismo que 0+**

In [ ]:
df["Type"].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [ ]:
df[df["Type"]=="0"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Hay un Outliner cuyo tipo es 0 y solo existen 2 tipos siendo de paga y gratis**

In [ ]:
df["Price"].value_counts()

Price
0           10040
$0.99         148
$2.99         129
$1.99          73
$4.99          72
            ...
$394.99         1
$1.26           1
Everyone        1
$1.20           1
$1.04           1
Name: count, Length: 93, dtype: int64

In [ ]:
df[df["Price"]=="Everyone"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Aqui hay un Outliner, el cual es Everyone**

In [ ]:
df["Content Rating"].value_counts()

Content Rating
Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
Name: count, dtype: int64

**Aqui el Unrated no es un Outliner, ya que, como indica su nombre solo dice indica que aun no tiene clasificación**

In [ ]:
df["Genres"].value_counts()

Genres
Tools                       842
Entertainment               623
Education                   549
Medical                     463
Business                    460
                           ...
Strategy;Education            1
Racing;Pretend Play           1
Communication;Creativity      1
February 11, 2018             1
Strategy;Creativity           1
Name: count, Length: 120, dtype: int64

In [ ]:
df[df["Genres"]=="February 11, 2018"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Aqui hay un Outliner el cual es una fecha, dato que no corresponde a la tabla de Genero**

In [ ]:
df["Last Updated"].value_counts()

Last Updated
August 3, 2018       326
August 2, 2018       304
July 31, 2018        294
August 1, 2018       285
July 30, 2018        211
                    ...
November 25, 2014      1
February 6, 2012       1
December 18, 2013      1
February 27, 2015      1
June 17, 2012          1
Name: count, Length: 1378, dtype: int64

**No existen Outliners**

In [ ]:
df["Current Ver"].value_counts()

Current Ver
Varies with device    1459
1.0                    809
1.1                    264
1.2                    178
2.0                    151
                      ...
2.8.6                    1
1.25.4                   1
15                       1
1.022                    1
1.0.0.96                 1
Name: count, Length: 2832, dtype: int64

**No existen Outliners**

In [ ]:
df["Android Ver"].value_counts()

Android Ver
4.1 and up            2451
4.0.3 and up          1501
4.0 and up            1375
Varies with device    1362
4.4 and up             980
2.3 and up             652
5.0 and up             601
4.2 and up             394
2.3.3 and up           281
2.2 and up             244
4.3 and up             243
3.0 and up             241
2.1 and up             134
1.6 and up             116
6.0 and up              60
7.0 and up              42
3.2 and up              36
2.0 and up              32
5.1 and up              24
1.5 and up              20
4.4W and up             12
3.1 and up              10
2.0.1 and up             7
8.0 and up               6
7.1 and up               3
5.0 - 8.0                2
4.0.3 - 7.1.1            2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: count, dtype: int64

**El unico Outliner seria "4.4W and up", ya que, solo deberia ser "4.4 and up"**

**Con todos los Outliners, nulos y duplicados revisados ya podemos comenzar a limpiar el data set y es lo que haremos en la siguiente sección**

|

|

|

|

|

**Creamos una copia con la que trabajar**

In [ ]:
df_clean=df.copy()

**Limpiaremos las filas duplicadas reiniciando el indice, para que, no ocurran saltos de indice al borrar estas filas**

ej;
1,2,3(fila duplicada),4

{se borran los duplicados}

1,2,4

In [ ]:
df_clean= df_clean.drop_duplicates().reset_index(drop=True)
df_clean.duplicated().sum()

np.int64(0)

|

|

In [ ]:
df_clean[df_clean['App']=="Life Made WI-Fi Touchscreen Photo Frame"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9990,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

**Si nos fijamos en los value counts anteriorers, existe una APP que se puede considerar basura y que contiene muchos Outliners que detectamos esta APP es Life Made WI-Fi Touchscreen Photo Frame, por esto es que decimios eliminarla**

In [ ]:
df_clean=df_clean.drop(9990)
df_clean[df_clean['App']=="Life Made WI-Fi Touchscreen Photo Frame"]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

**La APP no se la encuentra el codigo, porque, ya fue eliminada**

**Borrando Esta APP quitamos los Outliners de:**

-Genres

-Price

-Type

-Uno de los de Install

-Rating

-Category

|

|

|

**Recordando los resultados del codigo "df["Installs"].value_counts()" nos arrojaba 2 Outliner, de los cuales uno fue solucionado al eliminar la App anteriormente. El otro Outliner es 0+ el cual si las filas que contienen este valor nos daremos cuenta que realmente son App instaladas 0 veces, es por ello que transformaremos estas filas**

In [ ]:
df_clean['Installs'] = df_clean['Installs'].str.replace('0+', '0', regex=False)
#en el replace, el primer valor indica que buscamos y el segundo es su reemplazo
#regex indica que el cosas como el + es un caracter y no una suma por ejemplo

In [ ]:
df_clean[df_clean["Installs"]=="0+"]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

**No encuentra las APP's, ya que, fueron reemplazadas por 0**

|

|

In [ ]:
df["Android Ver"].value_counts()

Android Ver
4.1 and up            2451
4.0.3 and up          1501
4.0 and up            1375
Varies with device    1362
4.4 and up             980
2.3 and up             652
5.0 and up             601
4.2 and up             394
2.3.3 and up           281
2.2 and up             244
4.3 and up             243
3.0 and up             241
2.1 and up             134
1.6 and up             116
6.0 and up              60
7.0 and up              42
3.2 and up              36
2.0 and up              32
5.1 and up              24
1.5 and up              20
4.4W and up             12
3.1 and up              10
2.0.1 and up             7
8.0 and up               6
7.1 and up               3
5.0 - 8.0                2
4.0.3 - 7.1.1            2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: count, dtype: int64

**Revisando los resultados del codigo "df["Android Ver"].value_counts()" nos damos cuenta que solo tiene un Outliner siendo "4.4W and up" el cual simplemente sera reemplazado por "4.4 and up"**

In [ ]:
df_clean['Android Ver'] = df_clean['Android Ver'].str.replace('4.4W and up', '4.4 and up', regex=False)

**Verificamos los Cambios**

In [ ]:
df_clean[df_clean['Android Ver']=="4.4W and up"]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [ ]:
df_clean[df_clean['Android Ver']=="4.4 and up"].head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up

**Cambios Realizados Con Éxito**

**Con Esto Estaria "Limpio" el data Frame de valores Outliners y duplicados**

In [ ]:
df_clean.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

**LA SOLUCIÓN SERA REEMPLAZAR POR LA MODA, YA QUE, SON POCOS DATOS Y PRACTICAMENTE EL DATA SET NO SE VERA AFECTADO**

In [ ]:
df_clean['Type'] = df_clean['Type'].fillna(df_clean['Type'].mode()[0])

In [ ]:
df_clean['Current Ver'] = df_clean['Current Ver'].fillna(df_clean['Current Ver'].mode()[0])

In [ ]:
df_clean['Android Ver'] = df_clean['Android Ver'].fillna(df_clean['Android Ver'].mode()[0])

In [ ]:
df_clean

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10353,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10354,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10355,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10356,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10357,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

**Ahora Reemplazaremos el Rating Nulo por 0 SOLO de las APP's con 0 descargas, ya que, esto implica que si no hay descargas no hay reseñas**

In [ ]:
df_clean[(df_clean["Rating"].isnull()) & (df_clean['Installs'] == "0")]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4010,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5M,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",1.1,4.2 and up
4851,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7M,0,Paid,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up
5030,AP Series Solution Pro,FAMILY,NaN,0,7.4M,0,Paid,$1.99,Everyone,Education,"July 30, 2017",1.3,4.0 and up
5488,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33M,0,Paid,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up
6226,cronometra-br,PRODUCTIVITY,NaN,0,5.4M,0,Paid,$154.99,Everyone,Productivity,"November 24, 2017",1.0.0,4.1 and up
6965,Pekalongan CJ,SOCIAL,NaN,0,5.9M,0,Free,0,Teen,Social,"July 21, 2018",0.0.1,4.4 and up
7610,CX Network,BUSINESS,NaN,0,10M,0,Free,0,Everyone,Business,"August 6, 2018",1.3.1,4.1 and up
8143,Sweden Newspapers,NEWS_AND_MAGAZINES,NaN,0,2.1M,0,Free,0,Everyone,News & Magazines,"July 7, 2018",1.1,4.4 and up
8390,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8667,Command & Conquer: Rivals,FAMILY,NaN,0,Varies with device,0,Free,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device
8856,EG | Explore Folegandros,TRAVEL_AND_LOCAL,NaN,0,56M,0,Paid,$3.99,Everyone,Travel & Local,"January 22, 2017",1.1.1,4.1 and up
9238,EP Cook Book,MEDICAL,NaN,0,3.2M,0,Paid,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up
9424,Eu sou Rico,FINANCE,NaN,0,2.6M,0,Paid,$30.99,Everyone,Finance,"January 9, 2018",1.0,4.0 and up
9436,Eu Sou Rico,FINANCE,NaN,0,1.4M,0,Paid,$394.99,Everyone,Finance,"July 11, 2018",1.0,4.0.3 and up
9453,I'm Rich/Eu sou Rico/أنا غني/我很有錢,LIFESTYLE,NaN,0,40M,0,Paid,$399.99,Everyone,Lifestyle,"December 1, 2017",MONEY,4.1 and up

In [ ]:
condicion= (df_clean['Rating'].isnull()) & (df_clean['Installs'] == "0")

df_clean.loc[condicion, 'Rating'] = 0

**CON ESTO SE ELIMINAN LOS NULOS EXCEPTO POR LOS OTROS RATING**

In [ ]:
df_clean.isnull().sum()

App                  0
Category             0
Rating            1450
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          0
Android Ver          0
dtype: int64

In [ ]:
df_clean['Rating'].isnull().sum()

np.int64(1450)

**Ahora reemplazaremos los nulos de Rating por la mediana, esto debido a que son muchos datos como para borrar las filas y ademas solo tienen ese valor nulo o Outliner a diferencia de la APP anteriormente eliminada**

**Hemos elegido la Mediana debido a que es mas robusta frente a Outliners en este caso siendo los rating muy bajos como 1 y 2**

In [ ]:
df_clean['Rating'] = df_clean['Rating'].fillna(df_clean['Rating'].median())

**Ahora si, ya no quedan ni Outliners Ni Nulos**

In [ ]:
df_clean['Rating'].isnull().sum()

np.int64(0)

In [ ]:
df_clean.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

|

|

|

|

**Ahora cambiaremos la fecha de la ultima actualización de un String a Date para que sea coherence con el dato que representa**

In [ ]:
# Convertir la columna a tipo datetime
df_clean['Last Updated'] = pd.to_datetime(df_clean['Last Updated'], errors='coerce')

#Error es en caso de que encuentre algun valor no que no pueda trasformar, pero como no hay Outliners en esta columna no sera utilizado

In [ ]:
# Verificamos el tipo de dato (Dtype)
print(df_clean['Last Updated'].dtype)

datetime64[ns]

**Transformaremos la Columna de Price de String a float para poder manejar esta columna de forma correcta y mas sencilla, ya que, Esta columan solo es String para poner el Simbolo del Dolar $**

**IMPORTANTE BORRAR EL OUTLINER DE PRICE O DARA ERROR**

**Solo se ejecuta una vez ya que la segunda dara error al no tener String con los que trabajar**

In [ ]:
#Eliminamos el símbolo '$'
#Convertimos a float
df_clean['Price'] = df_clean['Price'].str.replace('$', '', regex=False).astype(float)

In [ ]:
# Verificamos el tipo de dato
print(df_clean['Price'].dtype)

float64

|

|

|

|

**METEMOS TODO LO QUE LLEVAMOS HASTA EL MOMENTO EN UN PIPELINE PARA NO TENER QUE EJECUTAR TODO EL CODIGO PARTE POR PARTE**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv("googleplaystore.csv")
df_clean=df.copy()
df_clean.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [ ]:
def pipeline_limpieza(df_input):
    df = df_input.copy()

    # 1. Eliminar duplicados y resetear índice
    df = df.drop_duplicates().reset_index(drop=True)

    # 2. Eliminar la app específica por nombre (Fila corrupta)
    # Esto es más seguro que usar .drop(9990)
    df = df[df['App'] != 'Life Made WI-Fi Touchscreen Photo Frame'].reset_index(drop=True)

    # 3. Transformaciones de Outliers en Installs y Android Ver
    df['Installs'] = df['Installs'].str.replace('0+', '0', regex=False)
    df['Android Ver'] = df['Android Ver'].str.replace('4.4W and up', '4.4 and up', regex=False)

    #4.Cambiamos el formato de las fechas a Date
    df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')

    # 5. Tratamiento de nulos (Imputación por Moda)
    df['Type'] = df['Type'].fillna(df['Type'].mode()[0])
    df['Current Ver'] = df['Current Ver'].fillna(df['Current Ver'].mode()[0])
    df['Android Ver'] = df['Android Ver'].fillna(df['Android Ver'].mode()[0])

    # 6. Corrección lógica: Rating = 0 cuando no hay instalaciones y es nulo
    condicion_nulos = (df['Rating'].isnull()) & (df['Installs']=="0")
    df.loc[condicion_nulos, 'Rating'] = 0

    #7. Reemplazamos Los Rating Nulos Por la median que es menos sensible a Outliners
    df['Rating'] = df['Rating'].fillna(df['Rating'].median())

    #8.Reemplazamos el precio por Float
    df['Price'] = df['Price'].str.replace('$', '', regex=False).astype(float)

    #9. Transformación con OneHotEncoder (Gratis=0, Paga=1)
    # drop='first' con Free/Paid dejará 'Paid' como la columna activa (1)
    encoder = OneHotEncoder(drop='first', sparse_output=False)
    df['Type'] = encoder.fit_transform(df[['Type']])

    # 10 Limpieza de 'Installs' (Eliminar '+' y ',')
    df['Installs'] = df['Installs'].str.replace('+', '').str.replace(',', '')
    # Manejar posibles errores (como la fila corrupta si es que existe)
    df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce').fillna(0).astype(int)


    # 12 Limpieza de 'Size' (Convertir todo a Megabytes)
    def clean_size(size):
        if 'M' in size:
            return float(size.replace('M', ''))
        elif 'k' in size:
            return float(size.replace('k', '')) / 1024
        elif 'Varies with device' in size:
            return np.nan
        return np.nan

    df['Size'] = df['Size'].apply(clean_size)

    # 13. Aplicar StandardScaler
    scaler = StandardScaler()
    # Creamos una nueva columna para no perder el valor original en MB
    df['Size_Scaled'] = scaler.fit_transform(df[['Size']])

    return df

#Ejecucion
df_clean = pipeline_limpieza(df)

# Verificación
print(f"¿Existe la app corrupta?: { 'Sí' if 'Life Made WI-Fi Touchscreen Photo Frame' in df_clean['App'].values else 'No'}")
print(f"Nulos en Rating después del ajuste: {df_clean['Rating'].isnull().sum()}")

¿Existe la app corrupta?: No
Nulos en Rating después del ajuste: 0

In [ ]:
# Verificamos el tipo de dato (Dtype)
print(df_clean['Last Updated'].dtype)

datetime64[ns]

In [ ]:
df_clean.isnull().sum()

App                  0
Category             0
Rating               0
Reviews              0
Size              1526
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          0
Android Ver          0
Size_Scaled       1526
dtype: int64

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10357 entries, 0 to 10356
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10357 non-null  object
 1   Category        10357 non-null  object
 2   Rating          10357 non-null  float64
 3   Reviews         10357 non-null  object
 4   Size            8831 non-null   float64
 5   Installs        10357 non-null  int64
 6   Type            10357 non-null  float64
 7   Price           10357 non-null  float64
 8   Content Rating  10357 non-null  object
 9   Genres          10357 non-null  object
 10  Last Updated    10357 non-null  datetime64[ns]
 11  Current Ver     10357 non-null  object
 12  Android Ver     10357 non-null  object
 13  Size_Scaled     8831 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 1.1+ MB

In [ ]:
df_clean["Type"].value_counts()

Type
0.0    9592
1.0     765
Name: count, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

# 2. Limpieza de 'Size' (Convertir todo a Megabytes)
def clean_size(size):
    if 'M' in size:
        return float(size.replace('M', ''))
    elif 'k' in size:
        return float(size.replace('k', '')) / 1024
    elif 'Varies with device' in size:
        return np.nan
    return np.nan

df['Size'] = df['Size'].apply(clean_size)

# 5. Estandarización de Texto (Categorías y Géneros a minúsculas para evitar duplicados por formato)
df['Category'] = df['Category'].str.lower()
df['Genres'] = df['Genres'].str.lower()


print("Estandarización completada. Tipos de datos finales:")
print(df.dtypes)
df.head()

Estandarización completada. Tipos de datos finales:
App                object
Category           object
Rating            float64
Reviews            object
Size              float64
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,art_and_design,4.1,159,19.0,"10,000+",Free,0,Everyone,art & design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,art_and_design,3.9,967,14.0,"500,000+",Free,0,Everyone,art & design;pretend play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art_and_design,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,art & design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,art_and_design,4.5,215644,25.0,"50,000,000+",Free,0,Teen,art & design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,art_and_design,4.3,967,2.8,"100,000+",Free,0,Everyone,art & design;creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
# Verificación
df_clean[['App', 'Size', 'Size_Scaled']].head()

                                                 App  Size  Size_Scaled
0     Photo Editor & Candy Camera & Grid & ScrapBook  19.0    -0.101485
1                                Coloring book moana  14.0    -0.323320
2  U Launcher Lite – FREE Live Cool Themes, Hide ...   8.7    -0.558465
3                              Sketch - Draw & Paint  25.0     0.164716
4              Pixel Draw - Number Art Coloring Book   2.8    -0.820230

In [ ]:
 df_clean.isnull().sum()

App                  0
Category             0
Rating               0
Reviews              0
Size              1526
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          0
Android Ver          0
Size_Scaled       1526
dtype: int64

### Exportar el DataFrame limpio
Utilizaremos `to_csv` para crear el archivo. El parámetro `index=False` evita que se guarde una columna adicional con los números de índice.

In [ ]:
# Guardar como CSV en el almacenamiento local de Colab
df_clean.to_csv('googleplaystore_clean.csv', index=False)

# Opcional: Descargar el archivo a tu ordenador
from google.colab import files
files.download('googleplaystore_clean.csv')